"use strict";
// Inject bundled PalBuilder context into a pal workspace WITHOUT clobbering user content.
//   - .claude/skills/palbuilder-frontend|backend/SKILL.md  (copied from bundle; palsync-owned)
//   - .claude/skills/design-core/...                       (OPT-IN via --with-design; default off)
//   - CLAUDE.palsync.md  = the proven pal-rules CLAUDE.md (palsync-owned; written fresh)
//   - CLAUDE.md          = the user's file, with a clearly-marked managed block inserted or
//                          refreshed in place. Everything outside the markers is preserved.
// Re-running setup only rewrites the managed block + palsync-owned files; a teammate's own
// CLAUDE.md notes survive.
const fs = require("fs/promises");
const path = require("path");

const BUNDLE_DIR = path.join(__dirname, "..", "..", "bundled-context");

// Always-on skills — injected every session (backend/bugfix sessions want these too).
const ALWAYS_ON_SKILLS = ["palbuilder-frontend", "palbuilder-backend"];

// Design skills — OPT-IN (--with-design; default off) so non-UI sessions stay lean. Each entry
// names a skill dir under bundled-context/skills/ and any companion asset files (paths may be
// nested, e.g. references/) that must ship alongside its SKILL.md. The folder name is the key —
// the SKILL.md frontmatter name (e.g. "palbuilder-design") is independent and not used here.
const DESIGN_SKILLS = [
    { name: "design-core", assets: ["references/components.md"] }
];
const BEGIN = "<!-- >>> palsync managed block — do not edit; regenerated by palsync setup >>> -->";
const END = "<!-- <<< palsync managed block <<< -->";

// The sync-etiquette section that teaches Claude the palsync workflow (decision: conversational).
function syncSection(palName) {
    return [
        "## palsync — sync etiquette (managed)",
        "",
        "This pal" + (palName ? " (**" + palName + "**)" : "") + " is connected to CloudPiston via the **palsync** MCP server and is **locked for your session**.",
        "",
        "**BEFORE writing any pal code, read the skill files** in `.claude/skills/` (`palbuilder-frontend`",
        "for pages/fragments/c: tags, `palbuilder-backend` for workflow .js). PalBuilder is a proprietary",
        "dialect you do NOT know from training — your defaults (object literals, `let`/`const`, normal",
        "HTML habits) produce code that saves but then FAILS to compile or render. The skills are the",
        "rules; follow them literally.",
        "",
        "The working loop:",
        "",
        "1. `pal_pull` before starting significant work. Pull is a safe sync: it preserves NEW",
        "   un-pushed files (and carries their `pal.json` entries forward), and it REFUSES — naming",
        "   the files — if it would overwrite un-pushed local edits.",
        "2. Write code following the skills. Then run **`pal_validate`** — an instant offline check",
        "   that catches the known PalBuilder breakers (object literals in workflows, `let`/`const`,",
        "   unclosed void tags, undocumented `c:` attributes, `${}` in inline scripts). Fix every",
        "   ERROR it reports; each finding tells you exactly how.",
        "3. **Offer to `pal_push`** when a meaningful change is done (palsync does not auto-push).",
        "   Push runs `pal_validate` automatically and refuses on errors — fix them rather than",
        "   reaching for `skipValidation`.",
        "4. After pushing workflow or UI changes, **offer to `pal_test`** — it runs the SERVER's own",
        "   validation and opens a live preview in the user's browser. You cannot see the preview",
        "   (the URL carries the user's credentials and is never given to you) — ask the user what",
        "   they see if you need to know.",
        "",
        "- If a push is **refused for drift** (someone saved on the server since your last pull), run `pal_pull`, reconcile, then push again.",
        "- Use `pal_status` to see whether the server is newer and who holds the lock (it names the real owner).",
        "- If a pal is locked by someone else (or checked out by you in PalBuilder), palsync reports the",
        "  owner and refuses. Do NOT casually override: overriding may destroy unsaved work. Override requires an",
        "  exact typed `confirmOverride` phrase; tell the user to unlock and close it in PalBuilder instead.",
        "- Datasets: you can create/update their TABLES with `pal_sync_datasets` (define in pal.json → sync). A normal",
        "  sync never deletes data; `recreate` does and needs a typed confirmation. Dataviews/data/datalists stay",
        "  PalBuilder-provisioned (preserved, never created).",
        "",
        "### Creating new files",
        "",
        "palsync's push builds its payload from `pal.json`. To create a NEW file: write the file to disk",
        "AND append a matching entry to `pal.json` — push then ships it automatically. To EDIT an existing",
        "file, just change it on disk (no manifest edit needed).",
        "",
        "**You CAN create** (write the file + append a `pal.json` entry): pages, fragments, scripts,",
        "emails, images, styles, attachments.",
        "",
        "**Pages, fragments, and scripts — ASK FIRST.** Before creating one, ask the user:",
        "\"Should this be **console** or **web**?\" Set `palType` from the answer (`palTypeConsole` or",
        "`palTypeWeb`) — it cannot be inferred from the folder. Emails/images/styles/attachments need no `palType`.",
        "",
        "New page → `pages.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Page\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"hideConsoleMenu\": false } }",
        "```",
        "New fragment → `fragments.entry` (string/filename include any subpath, e.g. `contacts/list.html`):",
        "```json",
        "{ \"string\": \"<path>\", \"Fragment\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<path>\", \"palType\": \"palTypeConsole\", \"parseable\": false } }",
        "```",
        "New script → `scripts.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Script\": { \"content\": \"\", \"contentType\": \"text/javascript\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"bookmarks\": \"\" } }",
        "```",
        "Leave `content` empty — push base64-encodes the file from disk.",
        "",
        "**You CANNOT create these — they are PalBuilder-only.** Do NOT create new **workflows**, **documents**,",
        "or **fonts**. The server rejects creating these via push and the rejection fails the ENTIRE push.",
        "If the user wants a new one, tell them to create it in **PalBuilder** first.",
        "",
        "> **palsync can still EDIT any of these once they exist in PalBuilder** — editing an existing workflow,",
        "> document, font, etc. on disk and pushing works normally. The PalBuilder-only rule is about CREATION only.",
        "",
        "### Datasets — you CAN create and update these (via `pal_sync_datasets`)",
        "",
        "A dataset has two parts: its DEFINITION (the schema) and its TABLE (the real storage).",
        "1. To create or change a dataset, write `datasets/<name>.json` (schema: `name`, `fields.DatasetField[]`",
        "   with `fieldName`/`fieldType`/`fieldSize`, `indexes`) AND add a matching `datasets.entry` to `pal.json`.",
        "2. Then call **`pal_sync_datasets`** — it saves the definition and provisions the actual table.",
        "   Editing the `.json` ALONE never creates the table; the sync step is what builds it.",
        "- A normal sync is SAFE: it creates the table if missing and applies additive changes, never deleting data.",
        "- `recreate` DROPS and rebuilds a table, DELETING ALL ITS ROWS. It requires an exact typed confirmation",
        "  and must never be used to make an additive change. Only suggest recreate when a column type must change",
        "  or a column is removed, and always warn the user it deletes all data first.",
        "- `dataviews`, `data`, `datalists` are still PalBuilder-provisioned — push/pull preserve them, don't create them.",
        "",
        "PalBuilder coding rules: see `@CLAUDE.palsync.md` and the skills in `.claude/skills/` (`palbuilder-frontend`, `palbuilder-backend`)."
    ].join("\n");
}

function managedBlock(palName) {
    return BEGIN + "\n" + syncSection(palName) + "\n" + END;
}

// Insert or replace the managed block, preserving all user content outside the markers.
function mergeClaudeMd(existing, palName) {
    const block = managedBlock(palName);
    if (existing == null) {
        return { content: block + "\n", mode: "created" };
    }
    const b = existing.indexOf(BEGIN);
    const e = existing.indexOf(END);
    if (b !== -1 && e !== -1 && e > b) {
        // Replace existing managed region in place; keep everything else verbatim.
        const before = existing.slice(0, b);
        const after = existing.slice(e + END.length);
        return { content: before + block + after, mode: "refreshed" };
    }
    // Append the block, preserving the user's existing content above it.
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return { content: existing + sep + block + "\n", mode: "appended" };
}

async function copyFile(src, dest) {
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.copyFile(src, dest);
}

async function readIfExists(p) {
    try { return await fs.readFile(p, "utf8"); }
    catch (e) { if (e.code === "ENOENT") return null; throw e; }
}

// The effective skill SET for a session, defined ONCE (always-on + design when opted in).
// Normalized to { name, assets } so always-on and design skills copy the same way. Per-agent
// code only varies the DESTINATION root — never the skill list.
function effectiveSkills(withDesign) {
    return ALWAYS_ON_SKILLS.map(name => ({ name, assets: [] }))
        .concat(withDesign ? DESIGN_SKILLS : []);
}

// Copy a skill set's SKILL.md (+ companion assets) into <rootDir>/skills/<name>/.
// rootDir is the agent's skills root: ".claude" (Claude) or ".agents" (Codex open standard).
async function copySkillSet(workspaceDir, rootDir, skills) {
    for (const s of skills) {
        await copyFile(path.join(BUNDLE_DIR, "skills", s.name, "SKILL.md"),
                       path.join(workspaceDir, rootDir, "skills", s.name, "SKILL.md"));
        for (const asset of (s.assets || [])) {
            await copyFile(path.join(BUNDLE_DIR, "skills", s.name, asset),
                           path.join(workspaceDir, rootDir, "skills", s.name, asset));
        }
    }
}

// Inject everything into workspaceDir. Returns a summary of what was written.
//   withDesign (default false) gates the opt-in design skills.
//   agent ("claude" default | "codex") decides which destinations get written. The Claude path
//   (.claude/skills + CLAUDE.md + CLAUDE.palsync.md) is ALWAYS written and byte-for-byte unchanged;
//   Codex ADDITIONALLY gets the same skills at the .agents/ open standard + an AGENTS.md carrying
//   the same managed instruction block (Claude Code does not read .agents/ or AGENTS.md — verified).
async function inject(workspaceDir, { palName, withDesign = false, agent = "claude" } = {}) {
    const skills = effectiveSkills(withDesign);

    // (A) CLAUDE path — always written, unchanged.
    await copySkillSet(workspaceDir, ".claude", skills);
    await copyFile(path.join(BUNDLE_DIR, "CLAUDE.md"), path.join(workspaceDir, "CLAUDE.palsync.md"));
    const claudePath = path.join(workspaceDir, "CLAUDE.md");
    const existingClaude = await readIfExists(claudePath);
    const mergedClaude = mergeClaudeMd(existingClaude, palName);
    await fs.writeFile(claudePath, mergedClaude.content, "utf8");

    // (B) CODEX path — additive, only for --agent codex. Same skills at the open-standard root,
    //     plus AGENTS.md with the same managed block (user content preserved, like CLAUDE.md).
    let agentsMd = null;
    if (agent === "codex") {
        await copySkillSet(workspaceDir, ".agents", skills);
        const agentsPath = path.join(workspaceDir, "AGENTS.md");
        const existingAgents = await readIfExists(agentsPath);
        const mergedAgents = mergeClaudeMd(existingAgents, palName);
        await fs.writeFile(agentsPath, mergedAgents.content, "utf8");
        agentsMd = { path: "AGENTS.md", mode: mergedAgents.mode, userContentPreserved: existingAgents != null };
    }

    const skillNames = skills.map(s => s.name);
    return {
        agent,
        skills: skillNames.map(name => path.join(".claude/skills", name, "SKILL.md")),
        agentSkills: agent === "codex" ? skillNames.map(name => path.join(".agents/skills", name, "SKILL.md")) : [],
        designInjected: withDesign,
        designSkills: withDesign ? DESIGN_SKILLS.map(d => d.name) : [],
        claudePalsync: "CLAUDE.palsync.md",
        claudeMd: { path: "CLAUDE.md", mode: mergedClaude.mode, userContentPreserved: existingClaude != null },
        agentsMd
    };
}

module.exports = { inject, mergeClaudeMd, managedBlock, syncSection, BEGIN, END, BUNDLE_DIR, ALWAYS_ON_SKILLS, DESIGN_SKILLS, effectiveSkills };
