"use strict";
// Inject bundled PalBuilder context into a pal workspace WITHOUT clobbering user content.
//   - .claude/skills/palbuilder-frontend|backend/SKILL.md  (copied from bundle; palsync-owned)
//   - CLAUDE.palsync.md  = the proven pal-rules CLAUDE.md (palsync-owned; written fresh)
//   - CLAUDE.md          = the user's file, with a clearly-marked managed block inserted or
//                          refreshed in place. Everything outside the markers is preserved.
// Re-running setup only rewrites the managed block + palsync-owned files; a teammate's own
// CLAUDE.md notes survive.
const fs = require("fs/promises");
const path = require("path");

const BUNDLE_DIR = path.join(__dirname, "..", "..", "bundled-context");
const BEGIN = "<!-- >>> palsync managed block — do not edit; regenerated by palsync setup >>> -->";
const END = "<!-- <<< palsync managed block <<< -->";

// The sync-etiquette section that teaches Claude the palsync workflow (decision: conversational).
function syncSection(palName) {
    return [
        "## palsync — sync etiquette (managed)",
        "",
        "This pal" + (palName ? " (**" + palName + "**)" : "") + " is connected to CloudPiston via the **palsync** MCP server and is **locked for your session**.",
        "",
        "- Pull the latest server state with `pal_pull` before starting significant work.",
        "- When you finish a meaningful change, **offer to `pal_push`** (palsync does not auto-push).",
        "- If a push is **refused for drift** (someone saved on the server since your last pull), run `pal_pull`, reconcile, then push again.",
        "- Use `pal_status` to see whether the server is newer and who holds the lock (it names the real owner).",
        "- If a pal is locked by someone else (or checked out by you in PalBuilder), palsync reports the",
        "  owner and refuses. Do NOT casually override: overriding may destroy unsaved work. Override requires an",
        "  exact typed `confirmOverride` phrase; tell the user to unlock and close it in PalBuilder instead.",
        "- Datasets/dataviews are provisioned in PalBuilder: push/pull preserve them but never create or destroy them.",
        "",
        "### Creating new files",
        "",
        "palsync's push builds its payload from `pal.json`. To create a NEW file: write the file to disk",
        "AND append a matching entry to `pal.json` — push then ships it automatically. To EDIT an existing",
        "file, just change it on disk (no manifest edit needed).",
        "",
        "**You CAN create** (write the file + append a `pal.json` entry): pages, fragments, scripts,",
        "emails, images, styles, attachments.",
        "",
        "**Pages, fragments, and scripts — ASK FIRST.** Before creating one, ask the user:",
        "\"Should this be **console** or **web**?\" Set `palType` from the answer (`palTypeConsole` or",
        "`palTypeWeb`) — it cannot be inferred from the folder. Emails/images/styles/attachments need no `palType`.",
        "",
        "New page → `pages.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Page\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"hideConsoleMenu\": false } }",
        "```",
        "New fragment → `fragments.entry` (string/filename include any subpath, e.g. `contacts/list.html`):",
        "```json",
        "{ \"string\": \"<path>\", \"Fragment\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<path>\", \"palType\": \"palTypeConsole\", \"parseable\": false } }",
        "```",
        "New script → `scripts.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Script\": { \"content\": \"\", \"contentType\": \"text/javascript\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"bookmarks\": \"\" } }",
        "```",
        "Leave `content` empty — push base64-encodes the file from disk.",
        "",
        "**You CANNOT create these — they are PalBuilder-only.** Do NOT create new **workflows**, **documents**,",
        "or **fonts**, and do NOT create **datasets/dataviews/data/datalists**. The server rejects creating",
        "these via push and the rejection fails the ENTIRE push. If the user wants a new one, tell them to",
        "create it in **PalBuilder** first.",
        "",
        "> **palsync can still EDIT any of these once they exist in PalBuilder** — editing an existing workflow,",
        "> document, font, etc. on disk and pushing works normally. The PalBuilder-only rule is about CREATION only.",
        "",
        "PalBuilder coding rules: see `@CLAUDE.palsync.md` and the skills in `.claude/skills/` (`palbuilder-frontend`, `palbuilder-backend`)."
    ].join("\n");
}

function managedBlock(palName) {
    return BEGIN + "\n" + syncSection(palName) + "\n" + END;
}

// Insert or replace the managed block, preserving all user content outside the markers.
function mergeClaudeMd(existing, palName) {
    const block = managedBlock(palName);
    if (existing == null) {
        return { content: block + "\n", mode: "created" };
    }
    const b = existing.indexOf(BEGIN);
    const e = existing.indexOf(END);
    if (b !== -1 && e !== -1 && e > b) {
        // Replace existing managed region in place; keep everything else verbatim.
        const before = existing.slice(0, b);
        const after = existing.slice(e + END.length);
        return { content: before + block + after, mode: "refreshed" };
    }
    // Append the block, preserving the user's existing content above it.
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return { content: existing + sep + block + "\n", mode: "appended" };
}

async function copyFile(src, dest) {
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.copyFile(src, dest);
}

async function readIfExists(p) {
    try { return await fs.readFile(p, "utf8"); }
    catch (e) { if (e.code === "ENOENT") return null; throw e; }
}

// Inject everything into workspaceDir. Returns a summary of what was written.
async function inject(workspaceDir, { palName } = {}) {
    // 1) skills (palsync-owned)
    const skills = ["palbuilder-frontend", "palbuilder-backend", "design-core"];
    for (const s of skills) {
        await copyFile(path.join(BUNDLE_DIR, "skills", s, "SKILL.md"),
                       path.join(workspaceDir, ".claude", "skills", s, "SKILL.md"));
    }
    // design-core ships a companion reference-theme.css the skill tells the agent to copy
    // into the pal's Styles/ — without it the skill references a file that isn't there.
    await copyFile(path.join(BUNDLE_DIR, "skills", "design-core", "reference-theme.css"),
                   path.join(workspaceDir, ".claude", "skills", "design-core", "reference-theme.css"));
    // 2) CLAUDE.palsync.md (palsync-owned pal rules, written fresh)
    await copyFile(path.join(BUNDLE_DIR, "CLAUDE.md"), path.join(workspaceDir, "CLAUDE.palsync.md"));

    // 3) CLAUDE.md (user file; only the managed block is touched)
    const claudePath = path.join(workspaceDir, "CLAUDE.md");
    const existing = await readIfExists(claudePath);
    const merged = mergeClaudeMd(existing, palName);
    await fs.writeFile(claudePath, merged.content, "utf8");

    return {
        skills: skills.map(s => path.join(".claude/skills", s, "SKILL.md")),
        claudePalsync: "CLAUDE.palsync.md",
        claudeMd: { path: "CLAUDE.md", mode: merged.mode, userContentPreserved: existing != null }
    };
}

module.exports = { inject, mergeClaudeMd, managedBlock, syncSection, BEGIN, END, BUNDLE_DIR };
